### ISSUE TITLE
Feature request: Direct shortcut to single click etc.

### ISSUE THREAD

**Issue by skobylite** [dexterleng/vimac-releases#1]
Loving this! 

**Feature request:** Setting a keyboard shortcut to just bring up the yellow prompts immediately, bypassing command line would be ideal. e.g. in vimium, where F is set to bring up the prompts rather than going through command line, typing 'ce', enter. 

So: a customisable keyboard shortcut for single click, right click, double click 👍.

Feature 2: Support for clicking on text fields to bring up the cursor.

**Comment by dexterleng** [comment]
This is already requested and WIP!

**Comment by BlueDrink9** [comment]
As a workaround, I'm using `skhd` with this macro:

`alt - f : skhd -k "cmd + shift - space" && skhd -k "c" && skhd -k "e" && skhd -k "return"`

This uses `alt+f` to activate single click

**Comment by dexterleng** [comment]
Use macros for now. The way you enter "commands" will probably change in future update(s) so I won't be implementing it now.

**Comment by skobylite** [comment]
> As a workaround, I'm using `skhd` with this macro:
> 
> `alt - f : skhd -k "cmd + shift - space" && skhd -k "c" && skhd -k "e" && skhd -k "return"`
> 
> This uses `alt+f` to activate single click

@BlueDrink9 - Could you explain this please? 

@dexterleng : IMO the entire benefit of the app is to minimise time and keystrokes, so going through a sequence of keystrokes to single click simply makes the trackpad the faster solution and renders the app redundant

**Comment by BlueDrink9** [comment]
Have you used [skhd](https://github.com/koekeishiya/skhd) before?

**Comment by skobylite** [comment]
Thanks - Just had a look, seems too clever for me! Will see if I can get the sequence working on Bettertouchtool, if not will figure skhd out.

**Comment by dexterleng** [comment]
> @dexterleng : IMO the entire benefit of the app is to minimise time and keystrokes, so going through a sequence of keystrokes to single click simply makes the trackpad the faster solution and renders the app redundant

Agreed. I need to find a "flow" that is fast but at the same time allows you to do more than just left click, right click, and double click. I rather spend time working on the "flow' now instead of implementing the shortcuts since you can use a macro.

**Comment by skobylite** [comment]
^ Makes sense - absolutely love this project and the work you've put into this so far! Looking forward to seeing how things grow

**Comment by dexterleng** [comment]
@skobylite v0.2.3 adds Focus mode, which let's you focus on text fields with hints. Is this what you requested for Feature 2?

https://vimacapp.com/v0-2-3-update/

**Comment by dexterleng** [comment]
Added! Now the controls are more like Vimium - hold SHIFT/CMD while typing the hint text to right/double click. Direct hotkeys to Hint and Scroll Mode.

Read the updated documentation:

https://vimacapp.com/how-to-use/
