### ISSUE TITLE
Archive vimac-0.2.3a.zip corrupt

### ISSUE THREAD

**Issue by jonasrk** [dexterleng/vimac-releases#10]
<img width="416" alt="Screenshot 2019-10-14 at 16 28 06" src="https://user-images.githubusercontent.com/2970342/66759362-664cd480-eea0-11e9-9f24-58e2e5352af9.png">

0.2.2 works fine.

**Comment by dexterleng** [comment]
@jonasrk weird. I just tested and it works.

**Comment by dexterleng** [comment]
@jonasrk can you use the autoupdater to update to v0.2.3?

**Comment by esambo** [comment]
I had the same problem. The _Vimac.app_ from the `vimac-0.2.3a.zip` cannot be Open'ed, but the one from the `vimac-0.2.2.app.zip` works fine, and properly supports the auto-updating

**Comment by dexterleng** [comment]
@esambo so you could update to v0.2.3?

**Comment by esambo** [comment]
@dexterleng Yes, `Check for updates` mentions: 
```
You're up-to-date! 
Vimac 0.2.3 is currently the newest version available.
```

**Comment by dexterleng** [comment]
Interesting. The deltas downloaded from the autoupdater is derived from the
supposedly corrupt file.

**Comment by dexterleng** [comment]
v0.3.0 should not be corrupt.
