### ISSUE TITLE
What is the latest release?

### ISSUE THREAD

**Issue by nikivdev** [dexterleng/vimac-releases#14]
The link I got in email

https://github.com/dexterleng/vimac-releases/raw/master/vimac-0.2.3a.zip

Is broken.

**Comment by dexterleng** [comment]
I renamed the file to remove the "a", and pretty sure I did update the email. You probably subscribed before I renamed the file.

**Comment by dexterleng** [comment]
Note that v0.2.3's zip may be corrupted. You can download v0.2.2 and update through the autoupdater meanwhile.
