### ISSUE TITLE
ESC does not exit scroll mode

### ISSUE THREAD

**Issue by TheLocehiliosan** [dexterleng/vimac-releases#16]
It appears that with 0.3.0 `ESC` exits "hint mode", but does not exit "scroll mode". In order to exit "scroll mode" I have to `CTRL-S`, then `ESC` (which is pretty clunky). Am I missing something?

**Comment by dexterleng** [comment]
@TheLocehiliosan Just tested and can confirm it's a missing feature. I'll add it in.

**Comment by dexterleng** [comment]
Fixed in v0.3.1!
