### ISSUE TITLE
Hints are unaligned when multiple displays are used.

### ISSUE THREAD

**Issue by NylonDiamond** [dexterleng/vimac-releases#20]
CTRL + Space shows the hints but they are all completely unaligned on all apps. They are shifted upward many pixels making the app useless. Not sure what would be causing this. 
![image](https://user-images.githubusercontent.com/19392284/68093987-8db81100-fe50-11e9-8eba-1c706ec4dc82.png)

**Comment by dexterleng** [comment]
Are you using a second display? I might have done the coordinate math wrong.

**Comment by NylonDiamond** [comment]
I have a 3 display setup. Currently using the app on the middle display.

**Comment by NylonDiamond** [comment]
I disabled my center display which is a different resolution than the other two monitors and it's working. When I reenable my middle monitor with the higher resolution, all the hints are shifted up on all monitors.

**Comment by dexterleng** [comment]
Ah ok. Thanks for determining the cause! Working on it.

**Comment by Stvad** [comment]
Ah, that's where they went! +1 impacted

**Comment by dexterleng** [comment]
@NylonDiamond  v0.3.2 fixes issues related to hint positioning with multiple displays. Let me know if the problem persists!

**Comment by NylonDiamond** [comment]
@dexterleng , that seemed to fix it. Good job
