### ISSUE TITLE
CTRL + space hint mode didn't work

### ISSUE THREAD

**Issue by trulytrojan** [dexterleng/vimac-releases#21]
right after installation I  tried the hint mode and it doesn't work.
Did I miss anything?
PS: accessibility access permission is configured already.

**Comment by dexterleng** [comment]
Are you using multiple displays? May be similar to #20.

**Comment by dexterleng** [comment]
v0.3.2 fixes issues related to hint positioning with multiple displays. Let me know if the problem persists!
