### ISSUE TITLE
Feature Request: Scroll Direction

### ISSUE THREAD

**Issue by TheLocehiliosan** [dexterleng/vimac-releases#22]
I would love an option to either:
- Swap the direction scrolling uses
- Choose if scrolling emulated the trackpad or the mouse.

Rationale: I use the app [Scroll Reverser](https://pilotmoon.com/scrollreverser/), which allows reversing the direction of scrolling. The app allows changing the mouse or the trackpad individually. To be changing the direction of the mouse feels more natural, but I leave the trackpad as it is, because that also seems natural.

However, because I reverse the scrolling of the mouse, Vimac scrolling does the opposite of what I would expect from Vim keybindings.

**Comment by dexterleng** [comment]
@TheLocehiliosan working on it.

**Comment by dexterleng** [comment]
@TheLocehiliosan added in v0.3.3!

**Comment by TheLocehiliosan** [comment]
@dexterleng Thanks for this. Seems to work, except I noticed scrolling with `u` and `d` are not reversed. I think maybe that was just missed.

**Comment by dexterleng** [comment]
@TheLocehiliosan ah forgot about that!

**Comment by dexterleng** [comment]
Addressed in v0.3.3.1. let me know if the problem persists.

**Comment by TheLocehiliosan** [comment]
Works great! I scrolled to the bottom of this page using Vimac. 👍
