### ISSUE TITLE
Build for Catalina

### ISSUE THREAD

**Issue by n3h3m** [dexterleng/vimac-releases#29]
I love to try out Vimac badly but I'm stuck with Catalina. Kindly let us know how long we wait for that experience?

**Comment by dexterleng** [comment]
What's the issue on Catalina? I have to get around to testing it.

**Comment by n3h3m** [comment]
Oh, I was getting this, never mind I somehow ended with enabling from the Accessibility settings. 

Nice, Vimac is totally cool, Especially love it's ability to actually moves the mouse upon where it was clicked. Liking it so far, Add more features :D
 
<img width="403" alt="Screenshot 2019-12-04 14 40 52" src="https://user-images.githubusercontent.com/1170505/70110794-4a95cb80-16a4-11ea-9d75-713867578609.png">

**Comment by dexterleng** [comment]
@n3h3m I'll have to get around to notarizing it to remove that warning. I'm glad you like it!
