### ISSUE TITLE
Scroll mode conflicts with full-screen preview's sidebar

### ISSUE THREAD

**Issue by xuxife** [dexterleng/vimac-releases#30]
Vimac places the cursor at left-bottom corner in scroll mode. 
That's where Preview.app in fullscreen triggers "sidebar" ("Thumbnails", "Table of Contents", etc).
Everytime I call scroll mode in fullscreen preview, I could scroll the page view for several seconds. After that, sidebar goes in and scrolls instead.

Maybe alternative cursor positions?

**Comment by dexterleng** [comment]
@xuxife Didn't think of that. Thanks for reporting!

I will probably hide the cursor in Scroll mode and center the cursor in the scroll area as a fix.
