### ISSUE TITLE
[Feature Request] Sth. like D/U scrolling to scroll a half page left/right

### ISSUE THREAD

**Issue by jonasrk** [dexterleng/vimac-releases#32]

**Comment by dexterleng** [comment]
Will do. I think'll map SHIFT-H/J/K/L to scroll by half of the screen horizontally/vertically.

**Comment by jonasrk** [comment]
Excellent! :)

**Comment by dexterleng** [comment]
Added in v0.3.5! Feel free to reopen if I'm missing something.
