### ISSUE TITLE
Feature Request: not exit hint mode after click？

### ISSUE THREAD

**Issue by tshu-w** [dexterleng/vimac-releases#34]
Most of the time we need to click more than once, maybe offer an option that hint mode not exit after the click(exit by press ESC and so on)?

**Comment by dexterleng** [comment]
I have thought about implementing this. The trouble is with view transitions and animations after clicking something. You do not want to trigger the hint finding too early and miss out on the new elements being drawn after the animations.

I think having a user configuration delay between a click and hint-finding could be the solution.

There is also the problem of hints showing up before you even decided what you want to click on and hints are blocking everything. That could be solved by having a button that hides hints while being held down.

**Comment by tshu-w** [comment]
yeah, it looks far more complicated than I thought about before. By the way, in the latest version(0.3.5), hint sometimes doesn't show in safari until you enter and exit scroll mode, I don't know if it's caused by this update: Keep hint text consistent when element tree is unchanged.

**Comment by dexterleng** [comment]
> hint sometimes doesn't show in safari until you enter and exit scroll mode,

Interesting, is this a random thing that happens occasionally or can you replicate this? I'm not facing such issues.

I doubt v0.3.5 is the problem since it just adds a simple sorting algorithm to the tree traversal.

**Comment by tshu-w** [comment]
> hint sometimes doesn't show in safari until you enter and exit scroll mode

This issue happens randomly. I would let you know if I find a way to replicate it.
