### ISSUE TITLE
Feature Request: force Vimac with English input

### ISSUE THREAD

**Issue by tshu-w** [dexterleng/vimac-releases#35]
Sometimes I call Vimac in Chinese input method and have to switch to English to make it work, is there any way to force Vimac calling with English input.

**Comment by dexterleng** [comment]
This is looks like a complicated problem that even vimium has yet to solve. One solution is to map physical keycodes to QWERTY/DVORAK/Whatever. Unfortunately I don't I will be able to solve this soon.

**Comment by tshu-w** [comment]
Since vimac is an app and not a browser plugin like vimium, it should be easier to achieve this? Alfred and LaunchBar provide this option. Or maybe is there any way to detect vimac is active so I can use other tools to change the input source. Currently, hammerspoon or keyboard maestro window trigger doesn't work.

**Comment by dexterleng** [comment]
Ah ok, in that case I'll look into how Alfred does it.
