### ISSUE TITLE
Feature Request: Control-Space again to disable hint-mode

### ISSUE THREAD

**Issue by marconetto** [dexterleng/vimac-releases#36]
To quick the hint-mode, esc needs to be pressed. It would be nice to press control-space again to exit the hint-mode.

**Comment by dexterleng** [comment]
working on it. do you find yourself cancelling hint-mode often?

**Comment by marconetto** [comment]
Thanks Dexter for the reply. Depending on the context yes. If I'm in the hint-mode and I see that the screen becomes a bit messy (too many options) I prefer to switch-off  the hint-mode. And I found more natural to press control-space again to toggle the hint-mode, instead of pressing another key; which in this case is esc.  Hope this clarifies request.  BTW, great work!! I use vimac all the time :)

**Comment by dexterleng** [comment]
Added in v0.3.6! Please reopen if I missed something.
