### ISSUE TITLE
Keep hint letter whenever possible

### ISSUE THREAD

**Issue by marconetto** [dexterleng/vimac-releases#37]
In vimium, when the website view is not changed, by enabling or disabling the hint mode, the hint letters seem continue the same. In vimac, by pressing control-space several times it is possible to see that sometimes the hint letters change.

**Comment by dexterleng** [comment]
i've implemented this and it will be available next update!

**Comment by dexterleng** [comment]
Added in v0.3.5! Feel free to reopen if I'm missing something.

**Comment by marconetto** [comment]
Great!! Thanks!
