### ISSUE TITLE
Contributing!

### ISSUE THREAD

**Issue by NolanChan** [dexterleng/vimac-releases#4]
Hey!

Just wanted to know if there will be a place where I could contribute code to this project! I would love to help bring vimium to mac :D 

-Nolan

**Comment by dexterleng** [comment]
@NolanChan I'm still considering open source. I plan on charging for the software, and will have to look into the implications of adopting the GPL license.

**Comment by dexterleng** [comment]
I have decided against open source. Support appears to be the main way open source projects make money, and I believe that can't be done with utility apps like Vimac.

**Comment by NolanChan** [comment]
No worries, thanks for letting me know! Looking forward to this project maturing :D
