### ISSUE TITLE
Link to Beta Download is broken in signup link https vs http

### ISSUE THREAD

**Issue by oschrenk** [dexterleng/vimac-releases#5]
> Thanks for signing up for the Vimac newsletter and beta programme.
> You can download Vimac Beta here.

Here was redirecting me to https://vimacapp.com/<signup-path> but since the website does not support https I couldn't reach the site until I manually changed to http (and then Chrome remembers )

**Comment by dexterleng** [comment]
That's interesting. Did not happen for me. Regardless, I just set up redirecting to HTTPs so this should not be a problem.
