### ISSUE TITLE
Feature request: Filter clickable links on default apps

### ISSUE THREAD

**Issue by oschrenk** [dexterleng/vimac-releases#6]
Great idea and work!

Currently, it seems that Vimac attaches a link to any clickable element in the UI. Especially in the Finder and in Mail it's an overwhelming amount of choices. It would be great if the app could filter out the ones with the same target, thus presenting fewer (overlapping) choices to the user.

**Comment by dexterleng** [comment]
I just finished a filter by element type feature! Update will drop sometime in the next
24h.

The command would be "ce b" if you wanted to show hints only for buttons

You can do unions:

`ce b;dt;r` (disclosure triangles + button + row). 

Space as a separator works too (b dt r)

Let me know what you think.

**Comment by dexterleng** [comment]
Unfortunately there isn't surefire way to know two elements have the same Target, to my knowledge.

**Comment by dexterleng** [comment]
@oschrenk may I know what mail app you use?

**Comment by dexterleng** [comment]
v0.2.2 Adds link filtering:

https://vimacapp.com/v0-2-2-d-and-u-scrolling-and-filtering-hints/

**Comment by dexterleng** [comment]
v0.3.6 shows hints only for elements that are "actionable". This drastically cuts down the number of hints shown. You can see this effect here:

https://twitter.com/vimacapp/status/1221474476732252160

I'll consider this solved. Please reopen if I'm missing something!
